/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.26
 * Generated at: 2018-11-24 15:34:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;
import com.unlimited.oj.util.*;
import com.unlimited.oj.model.*;
import com.unlimited.oj.service.*;
import org.springframework.context.ApplicationContext;
import org.springframework.web.context.support.WebApplicationContextUtils;
import org.apache.taglibs.standard.tag.common.fmt.BundleSupport;
import java.util.ResourceBundle;
import javax.servlet.jsp.jstl.fmt.LocalizationContext;

public final class mainFrame_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(20);
    _jspx_dependants.put("/WEB-INF/lib/displaytag-1.2.jar", Long.valueOf(1510546770000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1510546770000L));
    _jspx_dependants.put("jar:file:/C:/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/JServer/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("jar:file:/C:/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/JServer/WEB-INF/lib/sitemesh-2.2.1.jar!/META-INF/sitemesh-decorator.tld", Long.valueOf(1084607714000L));
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-2.0.1.jar", Long.valueOf(1510546770000L));
    _jspx_dependants.put("jar:file:/C:/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/JServer/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fn.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("jar:file:/C:/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/JServer/WEB-INF/lib/oscache-2.3.jar!/META-INF/taglib.tld", Long.valueOf(1141644300000L));
    _jspx_dependants.put("/common/taglibs.jsp", Long.valueOf(1527668059084L));
    _jspx_dependants.put("jar:file:/C:/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/JServer/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fmt.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("jar:file:/C:/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/JServer/WEB-INF/lib/spring-security-taglibs-2.0.1.jar!/META-INF/security.tld", Long.valueOf(1209703464000L));
    _jspx_dependants.put("/WEB-INF/lib/sitemesh-2.2.1.jar", Long.valueOf(1510546770000L));
    _jspx_dependants.put("jar:file:/C:/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/JServer/WEB-INF/lib/displaytag-1.2.jar!/META-INF/displaytag.tld", Long.valueOf(1230360346000L));
    _jspx_dependants.put("/WEB-INF/appfuse.tld", Long.valueOf(1510546770000L));
    _jspx_dependants.put("/WEB-INF/lib/oscache-2.3.jar", Long.valueOf(1510546770000L));
    _jspx_dependants.put("jar:file:/C:/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/JServer/WEB-INF/lib/sitemesh-2.2.1.jar!/META-INF/sitemesh-page.tld", Long.valueOf(1084607714000L));
    _jspx_dependants.put("/WEB-INF/lib/struts2-core-2.0.11.1.jar", Long.valueOf(1510546770000L));
    _jspx_dependants.put("jar:file:/C:/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/JServer/WEB-INF/lib/struts-menu-2.4.3.jar!/META-INF/struts-menu-el.tld", Long.valueOf(1180670192000L));
    _jspx_dependants.put("/WEB-INF/lib/struts-menu-2.4.3.jar", Long.valueOf(1510546770000L));
    _jspx_dependants.put("jar:file:/C:/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/JServer/WEB-INF/lib/struts2-core-2.0.11.1.jar!/META-INF/struts-tags.tld", Long.valueOf(1204458594000L));
    _jspx_dependants.put("jar:file:/C:/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/JServer/WEB-INF/lib/standard-1.1.2.jar!/META-INF/sql.tld", Long.valueOf(1098682290000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("com.unlimited.oj.model");
    _jspx_imports_packages.add("com.unlimited.oj.util");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("com.unlimited.oj.service");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.apache.taglibs.standard.tag.common.fmt.BundleSupport");
    _jspx_imports_classes.add("javax.servlet.jsp.jstl.fmt.LocalizationContext");
    _jspx_imports_classes.add("org.springframework.context.ApplicationContext");
    _jspx_imports_classes.add("org.springframework.web.context.support.WebApplicationContextUtils");
    _jspx_imports_classes.add("java.util.ResourceBundle");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.release();
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			"/error.jsp", true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"zh-CN\">\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("\t<title></title>\r\n");
      out.write("\t<link href=\"style/authority/main_css.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("\t<link href=\"style/authority/zTreeStyle.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"scripts/jquery/jquery-1.7.1.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"scripts/zTree/jquery.ztree.core-3.2.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"scripts/authority/commonAll.js\"></script>\r\n");
      out.write("\t\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t/**éåºç³»ç»**/\r\n");
      out.write("\t\tfunction logout(){\r\n");
      out.write("\t\t\tif(confirm(\"Quit?\")){\r\n");
      out.write("\t\t\t\twindow.location.href = \"/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appConfig['project.name']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/logout.jsp\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/**è·å¾å½åæ¥æ**/\r\n");
      out.write("\t\tfunction  getDate01(){\r\n");
      out.write("\t\t\tvar time = new Date();\r\n");
      out.write("\t\t\tvar myYear = time.getFullYear();\r\n");
      out.write("\t\t\tvar myMonth = time.getMonth()+1;\r\n");
      out.write("\t\t\tvar myDay = time.getDate();\r\n");
      out.write("\t\t\tif(myMonth < 10){\r\n");
      out.write("\t\t\t\tmyMonth = \"0\" + myMonth;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif(myDay < 10){\r\n");
      out.write("\t\t\t\tmyDay = \"0\" + myDay;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t//document.getElementById(\"yue_fen\").innerHTML =  myYear + \".\" + myMonth;\r\n");
      out.write("\t\t\tdocument.getElementById(\"day_day\").innerHTML =  myYear + \".\" + myMonth + \".\" + myDay;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t/* zTreeæä»¶å è½½ç®å½çå¤ç  */\r\n");
      out.write("\t\tvar zTree;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar setting = {\r\n");
      out.write("\t\t\t\tview: {\r\n");
      out.write("\t\t\t\t\tdblClickExpand: false,\r\n");
      out.write("\t\t\t\t\tshowLine: false,\r\n");
      out.write("\t\t\t\t\texpandSpeed: ($.browser.msie && parseInt($.browser.version)<=6)?\"\":\"fast\"\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tdata: {\r\n");
      out.write("\t\t\t\t\tkey: {\r\n");
      out.write("\t\t\t\t\t\tname: \"resourceName\"\r\n");
      out.write("\t\t\t\t\t},\r\n");
      out.write("\t\t\t\t\tsimpleData: {\r\n");
      out.write("\t\t\t\t\t\tenable:true,\r\n");
      out.write("\t\t\t\t\t\tidKey: \"resourceID\",\r\n");
      out.write("\t\t\t\t\t\tpIdKey: \"parentID\",\r\n");
      out.write("\t\t\t\t\t\trootPId: \"\"\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t},\r\n");
      out.write("\t\t\t\tcallback: {\r\n");
      out.write("\t// \t\t\t\tbeforeExpand: beforeExpand,\r\n");
      out.write("\t// \t\t\t\tonExpand: onExpand,\r\n");
      out.write("\t\t\t\t\tonClick: zTreeOnClick\t\t\t\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t \r\n");
      out.write("\t\tvar curExpandNode = null;\r\n");
      out.write("\t\tfunction beforeExpand(treeId, treeNode) {\r\n");
      out.write("\t\t\tvar pNode = curExpandNode ? curExpandNode.getParentNode():null;\r\n");
      out.write("\t\t\tvar treeNodeP = treeNode.parentTId ? treeNode.getParentNode():null;\r\n");
      out.write("\t\t\tfor(var i=0, l=!treeNodeP ? 0:treeNodeP.children.length; i<l; i++ ) {\r\n");
      out.write("\t\t\t\tif (treeNode !== treeNodeP.children[i]) {\r\n");
      out.write("\t\t\t\t\tzTree.expandNode(treeNodeP.children[i], false);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\twhile (pNode) {\r\n");
      out.write("\t\t\t\tif (pNode === treeNode) {\r\n");
      out.write("\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\tpNode = pNode.getParentNode();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif (!pNode) {\r\n");
      out.write("\t\t\t\tsinglePath(treeNode);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction singlePath(newNode) {\r\n");
      out.write("\t\t\tif (newNode === curExpandNode) return;\r\n");
      out.write("\t\t\tif (curExpandNode && curExpandNode.open==true) {\r\n");
      out.write("\t\t\t\tif (newNode.parentTId === curExpandNode.parentTId) {\r\n");
      out.write("\t\t\t\t\tzTree.expandNode(curExpandNode, false);\r\n");
      out.write("\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\tvar newParents = [];\r\n");
      out.write("\t\t\t\t\twhile (newNode) {\r\n");
      out.write("\t\t\t\t\t\tnewNode = newNode.getParentNode();\r\n");
      out.write("\t\t\t\t\t\tif (newNode === curExpandNode) {\r\n");
      out.write("\t\t\t\t\t\t\tnewParents = null;\r\n");
      out.write("\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t} else if (newNode) {\r\n");
      out.write("\t\t\t\t\t\t\tnewParents.push(newNode);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\tif (newParents!=null) {\r\n");
      out.write("\t\t\t\t\t\tvar oldNode = curExpandNode;\r\n");
      out.write("\t\t\t\t\t\tvar oldParents = [];\r\n");
      out.write("\t\t\t\t\t\twhile (oldNode) {\r\n");
      out.write("\t\t\t\t\t\t\toldNode = oldNode.getParentNode();\r\n");
      out.write("\t\t\t\t\t\t\tif (oldNode) {\r\n");
      out.write("\t\t\t\t\t\t\t\toldParents.push(oldNode);\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\tif (newParents.length>0) {\r\n");
      out.write("\t\t\t\t\t\t\tfor (var i = Math.min(newParents.length, oldParents.length)-1; i>=0; i--) {\r\n");
      out.write("\t\t\t\t\t\t\t\tif (newParents[i] !== oldParents[i]) {\r\n");
      out.write("\t\t\t\t\t\t\t\t\tzTree.expandNode(oldParents[i], false);\r\n");
      out.write("\t\t\t\t\t\t\t\t\tbreak;\r\n");
      out.write("\t\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t\t}else {\r\n");
      out.write("\t\t\t\t\t\t\tzTree.expandNode(oldParents[oldParents.length-1], false);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tcurExpandNode = newNode;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\r\n");
      out.write("\t\tfunction onExpand(event, treeId, treeNode) {\r\n");
      out.write("\t\t\tcurExpandNode = treeNode;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/** ç¨äºæè·èç¹è¢«ç¹å»çäºä»¶åè°å½æ°  **/\r\n");
      out.write("\t\tfunction zTreeOnClick(event, treeId, treeNode) {\r\n");
      out.write("\t\t\tvar zTree = $.fn.zTree.getZTreeObj(\"dleft_tab1\");\r\n");
      out.write("\t\t\tzTree.expandNode(treeNode, null, null, null, true);\r\n");
      out.write("\t// \t\tzTree.expandNode(treeNode);\r\n");
      out.write("\t\t\t// è§å®ï¼å¦ææ¯ç¶ç±»èç¹ï¼ä¸åè®¸åå»æä½\r\n");
      out.write("\t\t\tif(treeNode.isParent){\r\n");
      out.write("\t// \t\t\talert(\"ç¶ç±»èç¹æ æ³ç¹å»å¦...\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t// å¦æèç¹è·¯å¾ä¸ºç©ºæèä¸º\"#\"ï¼ä¸åè®¸åå»æä½\r\n");
      out.write("\t\t\tif(treeNode.accessPath==\"\" || treeNode.accessPath==\"#\"){\r\n");
      out.write("\t\t\t\t//alert(\"èç¹è·¯å¾ä¸ºç©ºæèä¸º'#'å¦...\");\r\n");
      out.write("\t\t\t\treturn false;\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t    // è·³å°è¯¥èç¹ä¸å¯¹åºçè·¯å¾, æå½åèµæºID(resourceID)ä¼ å°åå°ï¼åè¿Session\r\n");
      out.write("\t\t    rightMain(treeNode.accessPath);\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t    if( !treeNode.isParent ){\r\n");
      out.write("\t\t\t    $('#here_area').html('");
      if (_jspx_meth_fmt_005fmessage_005f1(_jspx_page_context))
        return;
      out.write(":&nbsp;<span style=\"color:#1A5CC6\">'+treeNode.getParentNode().resourceName+'&nbsp;>&nbsp;'+treeNode.resourceName+'</span>');\r\n");
      out.write("\t\t    }else{\r\n");
      out.write("\t\t\t    $('#here_area').html('");
      if (_jspx_meth_fmt_005fmessage_005f2(_jspx_page_context))
        return;
      out.write(":&nbsp;<span style=\"color:#1A5CC6\">'+treeNode.resourceName+'</span>');\r\n");
      out.write("\t\t    }\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/* ä¸æ¹èå */\r\n");
      out.write("\t\tfunction switchTab(tabpage,tabid){\r\n");
      out.write("\t\tvar oItem = document.getElementById(tabpage).getElementsByTagName(\"li\"); \r\n");
      out.write("\t\t    for(var i=0; i<oItem.length; i++){\r\n");
      out.write("\t\t        var x = oItem[i];    \r\n");
      out.write("\t\t        x.className = \"\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\tif('left_tab1' == tabid){\r\n");
      out.write("\t\t\t\t$(document).ajaxStart(onStart).ajaxSuccess(onStop);\r\n");
      out.write("\t\t\t\t// å¼æ­¥å è½½\"ä¸å¡æ¨¡å\"ä¸çèå\r\n");
      out.write("\t\t\t  \tloadMenu('application', 'dleft_tab1');\r\n");
      out.write("\t\t\t}else  if('left_tab2' == tabid){\r\n");
      out.write("\t\t\t\t$(document).ajaxStart(onStart).ajaxSuccess(onStop);\r\n");
      out.write("\t\t\t\t// å¼æ­¥å è½½\"å¶ä»\"ä¸çèå\r\n");
      out.write("\t\t\t\tloadMenu('config', 'dleft_tab1');\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(document).ready(function(){\r\n");
      out.write("\t\t\t$(document).ajaxStart(onStart).ajaxSuccess(onStop);\r\n");
      out.write("\t\t\t/** é»è®¤å¼æ­¥å è½½\"ä¸å¡æ¨¡å\"ç®å½  **/\r\n");
      out.write("\t\t\tloadMenu('application', \"dleft_tab1\");\r\n");
      out.write("\t\t\t// é»è®¤å±å¼ææèç¹\r\n");
      out.write("\t\t\tif( zTree ){\r\n");
      out.write("\t\t\t\t// é»è®¤å±å¼ææèç¹\r\n");
      out.write("\t\t\t\tzTree.expandAll(true);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction loadMenu(resourceType, treeObj){\r\n");
      out.write("\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\ttype:\"GET\",\r\n");
      out.write("\t\t\t\turl:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dynamicURL}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('/');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appConfig['project.name']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/common_menu_get_PUBLIC.html?resourceType=\" + resourceType,\r\n");
      out.write("\t\t\t\tdataType : \"json\",\r\n");
      out.write("\t\t\t\tsuccess:function(data){\r\n");
      out.write("\t\t\t\t\t// å¦æè¿åæ°æ®ä¸ä¸ºç©ºï¼å è½½\"ä¸å¡æ¨¡å\"ç®å½\r\n");
      out.write("\t\t\t\t\t//alert(data)\r\n");
      out.write("\t\t            if(data != null){\r\n");
      out.write("\t\t                // å°è¿åçæ°æ®èµç»zTree\r\n");
      out.write("\t\t\t\t\t\t$.fn.zTree.init($(\"#\"+treeObj), setting, data);\r\n");
      out.write("\t\t\t\t\t\tzTree = $.fn.zTree.getZTreeObj(treeObj);\r\n");
      out.write("\t\t                if( zTree ){\r\n");
      out.write("\t\t                    // é»è®¤å±å¼ææèç¹\r\n");
      out.write("\t\t                    zTree.expandAll(true);\r\n");
      out.write("\t\t                }\r\n");
      out.write("\t\t            }\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//ajax start function\r\n");
      out.write("\t\tfunction onStart(){\r\n");
      out.write("\t\t\t$(\"#ajaxDialog\").show();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t//ajax stop function\r\n");
      out.write("\t\tfunction onStop(){\r\n");
      out.write("\t// \t\t$(\"#ajaxDialog\").dialog(\"close\");\r\n");
      out.write("\t\t\t$(\"#ajaxDialog\").hide();\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("</head>\r\n");
      if (_jspx_meth_c_005fset_005f2(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fset_005f3(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');

        LocalizationContext locCtxt = BundleSupport.getLocalizationContext(pageContext);
        ResourceBundle bundle = locCtxt.getResourceBundle();

        pageContext.setAttribute("badgeImage", "");
 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\t\tfunction show() {    \r\n");
      out.write("\t\t    var objDiv = $(\"#mydiv\");\r\n");
      out.write("\t\t    $(objDiv).css(\"display\",\"block\");\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tfunction hide() {\r\n");
      out.write("\t\t    var objDiv = $(\"#mydiv\");\r\n");
      out.write("\t\t    $(objDiv).css(\"display\", \"none\");\r\n");
      out.write("\t\t} \r\n");
      out.write("\t\tsetTimeout(show,3000);\r\n");
      out.write("\t\tsetTimeout(hide,10000);\r\n");
      out.write("</script>\r\n");
      out.write("<style>\r\n");
      out.write("   .touming .font{ font-size:14px; color:#FF0}\r\n");
      out.write("  .tm11{position:relative; width:483; height:568;}\r\n");
      out.write(" .tm22{   position:absolute;  left:0px;   top:0px; width: 483px;  height: 568px;  }\r\n");
      out.write("  .alpha{filter:alpha(opacity=50);width:483px;} \r\n");
      out.write("</style>\r\n");

        pageContext.setAttribute("logo", ApplicationConfig.getValue("LoginLogo"));
        pageContext.setAttribute("mainPage", ApplicationConfig.getValue("mainPage"));

      out.write("\r\n");
      out.write("<body onload=\"getDate01()\">\r\n");
      out.write("    <div id=\"top\">\r\n");
      out.write("\t\t<div id=\"top_logo\" style=\"padding-left: 1px;\">\r\n");
      out.write("\t\t\t<img alt=\"logo\" src=\"images/common/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${logo}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" width=\"544\" height=\"49\" style=\"vertical-align:middle;\">\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<div id=\"top_links\">\r\n");
      out.write("\t\t\t<div id=\"top_op\">\r\n");
      out.write("\t\t\t\t<ul>\r\n");
      out.write("\t\t\t\t\t<li style=\"margin:20px;\">\r\n");
      out.write("\t\t\t\t\t\t<a onMouseOver=\"javascript:show();\" onMouseOut=hide(); style=\"cursor:hand\">\r\n");
      out.write("\t\t\t\t\t\t\t<img alt=\"User\" src=\"images/common/user.jpg\">\r\n");
      out.write("\t\t\t\t\t\t</a>\r\n");
      out.write("           ");

            String color = "#606060";

            pageContext.setAttribute("loginName", "");
            pageContext.setAttribute("color", color);
            
      out.write("\r\n");
      out.write("                    <b><font color=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${color}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('"');
      out.write('>');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${badgeImage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${loginName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</b>\r\n");
      out.write("                        ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            </font>                                                         \r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t\t<li>\r\n");
      out.write("\t\t\t\t\t\t<img alt=\"Today is\" src=\"images/common/date.jpg\">\r\n");
      out.write("\t\t\t\t\t\t<span id=\"day_day\"></span>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                ");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_c_005fif_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t</ul> \r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div id=\"top_close\">\r\n");
      out.write("\t\t\t\t<a href=\"javascript:void(0);\" onclick=\"logout();\" target=\"_parent\">\r\n");
      out.write("\t\t\t\t\t<img alt=\"QUIT\" title=\"QUIT\" src=\"images/common/close.jpg\" style=\"position: relative; top: 10px; left: 25px;\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("    <!-- side menu start -->\r\n");
      out.write("\t<div id=\"side\">\r\n");
      out.write("\t\t<div id=\"left_menu\">\r\n");
      out.write("\t\t \t<ul id=\"TabPage2\" style=\"height:200px; margin-top:50px;\">\r\n");
      out.write("\t\t\t\t<li id=\"left_tab1\" class=\"selected\" onClick=\"javascript:switchTab('TabPage2','left_tab1');\" title=\"application\">\r\n");
      out.write("\t\t\t\t\t<img alt=\"application\" title=\"application\" src=\"images/common/1_hover.jpg\" width=\"33\" height=\"31\">\r\n");
      out.write("\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t<li id=\"left_tab2\" onClick=\"javascript:switchTab('TabPage2','left_tab2');\" title=\"config\">\r\n");
      out.write("\t\t\t\t\t<img alt=\"config\" title=\"config\" src=\"images/common/2.jpg\" width=\"33\" height=\"31\">\r\n");
      out.write("\t\t\t\t</li>\t\t\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div id=\"nav_show\" style=\"position:absolute; bottom:0px; padding:10px;\">\r\n");
      out.write("\t\t\t\t<a href=\"javascript:;\" id=\"show_hide_btn\">\r\n");
      out.write("\t\t\t\t\t<img alt=\"Show/Hide\" title=\"Show/Hide\" src=\"images/common/nav_hide.png\" width=\"35\" height=\"35\">\r\n");
      out.write("\t\t\t\t</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t </div>\r\n");
      out.write("\t\t <div id=\"left_menu_cnt\">\r\n");
      out.write("\t\t \t<div id=\"nav_module\">\r\n");
      out.write("\t\t \t\t<img src=\"images/common/module_1.png\" width=\"210\" height=\"58\"/>\r\n");
      out.write("\t\t \t</div>\r\n");
      out.write("\t\t \t<div id=\"nav_resource\">\r\n");
      out.write("\t\t \t\t<ul id=\"dleft_tab1\" class=\"ztree\"></ul>\r\n");
      out.write("\t\t \t</div>\r\n");
      out.write("\t\t </div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$('#TabPage2 li').click(function(){\r\n");
      out.write("\t\t\t\tvar index = $(this).index();\r\n");
      out.write("\t\t\t\t$(this).find('img').attr('src', 'images/common/'+ (index+1) +'_hover.jpg');\r\n");
      out.write("\t\t\t\t$(this).css({background:'#fff'});\r\n");
      out.write("\t\t\t\t$('#nav_module').find('img').attr('src', 'images/common/module_'+ (index+1) +'.png');\r\n");
      out.write("\t\t\t\t$('#TabPage2 li').each(function(i, ele){\r\n");
      out.write("\t\t\t\t\tif( i!=index ){\r\n");
      out.write("\t\t\t\t\t\t$(ele).find('img').attr('src', 'images/common/'+ (i+1) +'.jpg');\r\n");
      out.write("\t\t\t\t\t\t$(ele).css({background:'#303030'});\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t\t// æ¾ç¤ºä¾§è¾¹æ \r\n");
      out.write("\t\t\t\tswitchSysBar(true);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t// æ¾ç¤ºéèä¾§è¾¹æ \r\n");
      out.write("\t\t\t$(\"#show_hide_btn\").click(function() {\r\n");
      out.write("\t\t        switchSysBar();\r\n");
      out.write("\t\t    });\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t/**éèæèæ¾ç¤ºä¾§è¾¹æ **/\r\n");
      out.write("\t\tfunction switchSysBar(flag){\r\n");
      out.write("\t\t\tvar side = $('#side');\r\n");
      out.write("\t        var left_menu_cnt = $('#left_menu_cnt');\r\n");
      out.write("\t\t\tif( flag==true ){\t// flag==true\r\n");
      out.write("\t\t\t\tleft_menu_cnt.show(500, 'linear');\r\n");
      out.write("\t\t\t\tside.css({width:'280px'});\r\n");
      out.write("\t\t\t\t$('#top_nav').css({width:'77%', left:'304px'});\r\n");
      out.write("\t        \t$('#main').css({left:'280px'});\r\n");
      out.write("\t\t\t}else{\r\n");
      out.write("\t\t        if ( left_menu_cnt.is(\":visible\") ) {\r\n");
      out.write("\t\t\t\t\tleft_menu_cnt.hide(10, 'linear');\r\n");
      out.write("\t\t\t\t\tside.css({width:'60px'});\r\n");
      out.write("\t\t        \t$('#top_nav').css({width:'100%', left:'60px', 'padding-left':'28px'});\r\n");
      out.write("\t\t        \t$('#main').css({left:'60px'});\r\n");
      out.write("\t\t        \t$(\"#show_hide_btn\").find('img').attr('src', 'images/common/nav_show.png');\r\n");
      out.write("\t\t        } else {\r\n");
      out.write("\t\t\t\t\tleft_menu_cnt.show(500, 'linear');\r\n");
      out.write("\t\t\t\t\tside.css({width:'280px'});\r\n");
      out.write("\t\t\t\t\t$('#top_nav').css({width:'77%', left:'304px', 'padding-left':'0px'});\r\n");
      out.write("\t\t        \t$('#main').css({left:'280px'});\r\n");
      out.write("\t\t        \t$(\"#show_hide_btn\").find('img').attr('src', 'images/common/nav_hide.png');\r\n");
      out.write("\t\t        }\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("    <!-- side menu start -->\r\n");
      out.write("    <div id=\"top_nav\">\r\n");
      out.write("    <span id=\"here_area\">");
      if (_jspx_meth_fmt_005fmessage_005f6(_jspx_page_context))
        return;
      out.write(":&nbsp;");
      if (_jspx_meth_fmt_005fmessage_005f7(_jspx_page_context))
        return;
      out.write("</span>\r\n");
      out.write("\t</div>\r\n");
      out.write("    <div id=\"main\">\r\n");
      out.write("      \t<iframe name=\"right\" id=\"rightMain\" src=\"/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appConfig['project.name']}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write('/');
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${mainPage}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(".html\" frameborder=\"no\" scrolling=\"auto\" width=\"100%\" height=\"100%\" allowtransparency=\"true\"/>\r\n");
      out.write("    </div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("   \r\n");
      out.write(" ");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f0.setParent(null);
    // /common/taglibs.jsp(15,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setVar("ctx");
    // /common/taglibs.jsp(15,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f0.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
    if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f1.setParent(null);
    // /common/taglibs.jsp(16,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f1.setVar("datePattern");
    int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
    if (_jspx_eval_c_005fset_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      if (_jspx_eval_c_005fset_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.pushBody();
        _jspx_th_c_005fset_005f1.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
        _jspx_th_c_005fset_005f1.doInitBody();
      }
      do {
        if (_jspx_meth_fmt_005fmessage_005f0(_jspx_th_c_005fset_005f1, _jspx_page_context))
          return true;
        int evalDoAfterBody = _jspx_th_c_005fset_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
      if (_jspx_eval_c_005fset_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
        out = _jspx_page_context.popBody();
      }
    }
    if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.reuse(_jspx_th_c_005fset_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar.reuse(_jspx_th_c_005fset_005f1);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fset_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fset_005f1);
    // /common/taglibs.jsp(16,25) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f0.setKey("date.format");
    int _jspx_eval_fmt_005fmessage_005f0 = _jspx_th_fmt_005fmessage_005f0.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f0);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f1 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f1.setParent(null);
    // /WEB-INF/pages/mainFrame.jsp(158,29) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f1.setKey("label.currentposition");
    int _jspx_eval_fmt_005fmessage_005f1 = _jspx_th_fmt_005fmessage_005f1.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f1);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f2 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f2.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f2.setParent(null);
    // /WEB-INF/pages/mainFrame.jsp(160,29) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f2.setKey("label.currentposition");
    int _jspx_eval_fmt_005fmessage_005f2 = _jspx_th_fmt_005fmessage_005f2.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f2 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f2.setParent(null);
    // /WEB-INF/pages/mainFrame.jsp(227,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f2.setVar("currentUser");
    // /WEB-INF/pages/mainFrame.jsp(227,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f2.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${currentUser}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fset_005f2 = _jspx_th_c_005fset_005f2.doStartTag();
    if (_jspx_th_c_005fset_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f2);
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f3 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    _jspx_th_c_005fset_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fset_005f3.setParent(null);
    // /WEB-INF/pages/mainFrame.jsp(228,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f3.setVar("project_name");
    // /WEB-INF/pages/mainFrame.jsp(228,0) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fset_005f3.setValue((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appConfig['project.name']}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
    int _jspx_eval_c_005fset_005f3 = _jspx_th_c_005fset_005f3.doStartTag();
    if (_jspx_th_c_005fset_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f0.setParent(null);
    // /WEB-INF/pages/mainFrame.jsp(277,24) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appConfig['PlatformSecurityLevel']>0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
    if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                           \r\n");
        out.write("                        ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f1.setParent(null);
    // /WEB-INF/pages/mainFrame.jsp(286,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appConfig['PlatformSecurityLevel']==0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
    if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                  \t<li>\r\n");
        out.write("                      <font color=red>");
        if (_jspx_meth_fmt_005fmessage_005f3(_jspx_th_c_005fif_005f1, _jspx_page_context))
          return true;
        out.write("</font>\r\n");
        out.write("                    </li>\r\n");
        out.write("                ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f3 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f3.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f1);
    // /WEB-INF/pages/mainFrame.jsp(288,38) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f3.setKey("label.level.0");
    int _jspx_eval_fmt_005fmessage_005f3 = _jspx_th_fmt_005fmessage_005f3.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f3);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f2.setParent(null);
    // /WEB-INF/pages/mainFrame.jsp(291,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appConfig['PlatformSecurityLevel']==1}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
    if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                  \t<li>\r\n");
        out.write("                      <font color=orange>");
        if (_jspx_meth_fmt_005fmessage_005f4(_jspx_th_c_005fif_005f2, _jspx_page_context))
          return true;
        out.write("</font>\r\n");
        out.write("                    </li>\r\n");
        out.write("                ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f4 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f4.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f2);
    // /WEB-INF/pages/mainFrame.jsp(293,41) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f4.setKey("label.level.1");
    int _jspx_eval_fmt_005fmessage_005f4 = _jspx_th_fmt_005fmessage_005f4.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f4);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f3.setParent(null);
    // /WEB-INF/pages/mainFrame.jsp(296,16) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appConfig['PlatformSecurityLevel']==2}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
    if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("                  \t<li>\r\n");
        out.write("                      <font color=blue>");
        if (_jspx_meth_fmt_005fmessage_005f5(_jspx_th_c_005fif_005f3, _jspx_page_context))
          return true;
        out.write("</font>\r\n");
        out.write("                    </li>\r\n");
        out.write("                ");
        int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f3, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f5 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f5.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f3);
    // /WEB-INF/pages/mainFrame.jsp(298,39) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f5.setKey("label.level.2");
    int _jspx_eval_fmt_005fmessage_005f5 = _jspx_th_fmt_005fmessage_005f5.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f5);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f5);
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
    _jspx_th_c_005fif_005f4.setParent(null);
    // /WEB-INF/pages/mainFrame.jsp(301,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${appConfig['PlatformSecurityLevel']>0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
    int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
    if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
      do {
        out.write("\r\n");
        out.write("\t\t\t\t\t<div id=\"mydiv\" style=\" padding:1px 10px 1px 10px;  z-index:9999;width:200px;height:80px;position:absolute;display:none;border:1px;background-color:");
        out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${color}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
        out.write(";\">\r\n");
        out.write("\t\t\t\t\t\t\r\n");
        out.write("\t\t\t\t\t</div>\r\n");
        out.write("\t\t\t\t");
        int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
        if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
          break;
      } while (true);
    }
    if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f6 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f6.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f6.setParent(null);
    // /WEB-INF/pages/mainFrame.jsp(396,25) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f6.setKey("label.currentposition");
    int _jspx_eval_fmt_005fmessage_005f6 = _jspx_th_fmt_005fmessage_005f6.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f6);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f6);
    return false;
  }

  private boolean _jspx_meth_fmt_005fmessage_005f7(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:message
    org.apache.taglibs.standard.tag.rt.fmt.MessageTag _jspx_th_fmt_005fmessage_005f7 = (org.apache.taglibs.standard.tag.rt.fmt.MessageTag) _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.MessageTag.class);
    _jspx_th_fmt_005fmessage_005f7.setPageContext(_jspx_page_context);
    _jspx_th_fmt_005fmessage_005f7.setParent(null);
    // /WEB-INF/pages/mainFrame.jsp(396,74) name = key type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_fmt_005fmessage_005f7.setKey("mainMenu.title");
    int _jspx_eval_fmt_005fmessage_005f7 = _jspx_th_fmt_005fmessage_005f7.doStartTag();
    if (_jspx_th_fmt_005fmessage_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f7);
      return true;
    }
    _005fjspx_005ftagPool_005ffmt_005fmessage_0026_005fkey_005fnobody.reuse(_jspx_th_fmt_005fmessage_005f7);
    return false;
  }
}
